version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "JeanKadang"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "npm"
    assignees:
      - "JeanKadang"
    commit-message:
      prefix: "deps"
