// Builds docs/TECHNOLOGY_RADAR.md from the role catalogue (#172).
// Zero dependencies — `npm run build-radar` (or `--dry` to preview).
//
// What it measures, precisely: how many roles expect a technology, and at
// what proficiency. It looks only inside the Technology Proficiency Levels
// block, where each bullet already sits under a tier heading. A product
// named anywhere else in a role file — in Remote Work Considerations, say —
// says nothing about the skill expected of the person, and is ignored.
// "Microsoft Teams" appears in 220 role files and in 7 proficiency bullets;
// only the 7 belong on a radar.
//
// Rings are derived from the tier mix, not curated:
//
//   Adopt   expected at Expert or Proficient in 10 or more roles
//   Trial   expected at Expert or Proficient in fewer than 10
//   Assess  named mostly at Working Knowledge or Awareness
//   Hold    NOT DERIVABLE — see the note written into the document
'use strict';

const fs = require('fs');
const path = require('path');
const { listRoleFiles } = require('./seed-kpi-targets');
const { REFERENCE_DOC_PATTERN } = require('../roleMeta');

const ROOT      = path.join(__dirname, '..');
const ROLES_DIR = process.env.ROLES_DIR ? path.resolve(process.env.ROLES_DIR) : path.join(ROOT, 'Roles');
const VOCAB     = path.join(ROOT, 'data', 'technologies.json');
const OUT       = path.join(ROOT, 'docs', 'TECHNOLOGY_RADAR.md');
const DRY       = process.argv.includes('--dry');

const TIERS = ['Expert', 'Proficient', 'Working Knowledge', 'Awareness'];
const ADOPT_THRESHOLD = 10;

function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// Word-boundary match that tolerates the punctuation these bullets use.
// \b is no good here: ".NET" and "C++" have no word boundary at the edges.
function aliasRe(alias) {
  return new RegExp('(^|[^A-Za-z0-9])' + escapeRe(alias) + '([^A-Za-z0-9]|$)', 'i');
}

// Every proficiency bullet in a role, paired with the tier it sits under.
function proficiencyBullets(text) {
  const out = [];
  let tier = null;
  for (const line of text.split('\n')) {
    const head = line.match(/^\*\*(Expert|Proficient|Working Knowledge|Awareness)[^*]*\*\*/);
    if (head) { tier = head[1]; continue; }
    if (/^##\s/.test(line)) { tier = null; continue; }
    if (!tier) continue;
    const bullet = line.match(/^-\s+(.*\S)\s*$/);
    if (bullet) out.push({ tier, text: bullet[1] });
  }
  return out;
}

function ringFor(tiers) {
  const strong = tiers.filter(t => t === 'Expert' || t === 'Proficient').length;
  if (strong === 0) return 'Assess';
  return strong >= ADOPT_THRESHOLD ? 'Adopt' : 'Trial';
}

function build({ rolesDir = ROLES_DIR } = {}) {
  const vocab = JSON.parse(fs.readFileSync(VOCAB, 'utf8'));
  const matchers = vocab.technologies.map(t => ({ ...t, res: t.aliases.map(aliasRe) }));

  for (const t of matchers) { t.roles = new Set(); t.tiers = []; }

  // Standards documents live beside the roles but describe policy, not a
  // person, so they carry no proficiency expectations to count.
  const files = listRoleFiles(rolesDir).filter(f => !REFERENCE_DOC_PATTERN.test(path.basename(f)));
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8').replace(/^﻿/, '').replace(/\r\n/g, '\n');
    const role = path.basename(file, '.md');
    for (const { tier, text: bullet } of proficiencyBullets(text)) {
      for (const t of matchers) {
        if (!t.res.some(re => re.test(bullet))) continue;
        t.roles.add(role);
        t.tiers.push(tier);
      }
    }
  }

  const entries = matchers
    .map(t => {
      const strongest = t.tiers.slice().sort((a, b) => TIERS.indexOf(a) - TIERS.indexOf(b));
      return {
        name: t.name,
        quadrant: t.quadrant,
        roles: t.roles.size,
        ring: ringFor(t.tiers),
        tier: strongest.length ? strongest[Math.floor(strongest.length / 2)] : null,
        expert: t.tiers.filter(x => x === 'Expert').length,
        proficient: t.tiers.filter(x => x === 'Proficient').length,
      };
    })
    .filter(t => t.roles > 0)
    .sort((a, b) => b.roles - a.roles || a.name.localeCompare(b.name));

  const absent = matchers.filter(t => t.roles.size === 0).map(t => t.name);
  return { entries, absent, roleCount: files.length, quadrants: vocab.quadrants };
}

function render({ entries, absent, roleCount, quadrants }) {
  const stamp = new Date().toISOString().slice(0, 7);
  const L = [];
  L.push('# Technology radar');
  L.push('');
  L.push('<!-- Generated by scripts/build-radar.js — do not edit by hand. -->');
  L.push('<!-- Run `npm run build-radar` after changing data/technologies.json or a role file. -->');
  L.push('');
  L.push(`Derived from the **Technology Proficiency Levels** sections of ${roleCount} role definitions, against the curated vocabulary in \`data/technologies.json\`. Generated ${stamp}.`);
  L.push('');
  L.push('## What this radar says, and what it does not');
  L.push('');
  L.push('**It says what the organisation staffs for.** A technology sits here because role definitions expect people to be good at it, and its ring reflects how many roles expect that and at what depth:');
  L.push('');
  L.push('| Ring | Meaning here |');
  L.push('|---|---|');
  L.push(`| **Adopt** | Expected at Expert or Proficient level in ${ADOPT_THRESHOLD} or more roles |`);
  L.push(`| **Trial** | Expected at Expert or Proficient level in fewer than ${ADOPT_THRESHOLD} roles |`);
  L.push('| **Assess** | Named mostly at Working Knowledge or Awareness level |');
  L.push('| **Hold** | *Empty, and not derivable — see below* |');
  L.push('');
  L.push('**It does not say what to adopt.** A conventional radar carries a recommendation; this one carries an observation. Nothing in a role definition says "stop using this", so **the Hold ring has no source in this repository** and is deliberately empty rather than guessed. Filling it is a judgement someone must make and sign, not something the catalogue can be squeezed to produce.');
  L.push('');
  L.push('A count here is also not a licence count or a spend signal. It counts role definitions, and a role definition may describe one person or thirty.');
  L.push('');

  for (const q of quadrants) {
    const inQ = entries.filter(e => e.quadrant === q);
    if (!inQ.length) continue;
    L.push(`## ${q}`);
    L.push('');
    L.push('| Technology | Ring | Roles | Expert | Proficient |');
    L.push('|---|---|---:|---:|---:|');
    for (const e of inQ) L.push(`| ${e.name} | ${e.ring} | ${e.roles} | ${e.expert} | ${e.proficient} |`);
    L.push('');
  }

  L.push('## Summary');
  L.push('');
  const byRing = ring => entries.filter(e => e.ring === ring).length;
  L.push('| Ring | Technologies |');
  L.push('|---|---:|');
  L.push(`| Adopt | ${byRing('Adopt')} |`);
  L.push(`| Trial | ${byRing('Trial')} |`);
  L.push(`| Assess | ${byRing('Assess')} |`);
  L.push('| Hold | 0 — not derivable |');
  L.push('');

  if (absent.length) {
    L.push('## In the vocabulary, absent from the catalogue');
    L.push('');
    L.push('Named in `data/technologies.json` but appearing in no proficiency bullet. Either nobody is expected to know it, or a role definition is missing it:');
    L.push('');
    for (const a of absent) L.push(`- ${a}`);
    L.push('');
  }
  // Sections are built with trailing blanks, which markdownlint's MD012
  // rejects where two meet. Collapsing once here beats making every push
  // site think about its neighbour.
  return L.join('\n').replace(/\n{3,}/g, '\n\n').replace(/\n+$/, '') + '\n';
}

function main() {
  const data = build();
  const out = render(data);
  const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : null;
  const changed = existing !== out;

  if (changed && !DRY) fs.writeFileSync(OUT, out, 'utf8');
  console.log(DRY ? '[dry run]' : '[written]',
    `${data.entries.length} technologies across ${data.quadrants.length} quadrants`,
    `· ${data.absent.length} in the vocabulary with no proficiency mention`,
    changed ? '· document differs' : '· document already current');
}

if (require.main === module) main();

module.exports = { build, render, proficiencyBullets, aliasRe, ringFor, ADOPT_THRESHOLD };
